### PR TITLE
Cleanup (clippy warnings)

### PR DESCRIPTION
**Pull request by hoijui**
Almost all of these changes were suggested by:

```
cargo clippy --release -- --deny clippy::pedantic
```

Exceptions:

* Moves expression.rs to expression/mod.rs
* Moves text.rs to text/mod.rs

### CODE REVIEW

**Comment by Jake-Shadle** [comment]
Please don't rename the files to mod.rs, mod.rs makes the code organization more unclear and less easy to grep through (though it's not a problem with this repo).

**Comment by Jake-Shadle** [comment]
While I like the idea of fixing these lints, the problem is that we will never run with pedantic in a CI situation since we will only ever check for the lints specified in the lib.rs file, but I suppose this is fine as a one time change.

**Comment by hoijui** [comment]
> While I like the idea of fixing these lints, the problem is that we will never run with pedantic in a CI situation since we will only ever check for the lints specified in the lib.rs file, but I suppose this is fine as a one time change.

hmmm.. I noticed that pedantic takes quite some more time to run then your clippy settings.. is it because of this?
or rather because you don't want to scare-of contributors, or.. something else? (I am still quite new to rust)

**Comment by hoijui** [comment]
I undid the renames to mod.rs, and added https://github.com/EmbarkStudios/spdx/pull/47/commits/aad225e57391ff78f97bfd18ee865297d8976f60
.. though that file (`src/text.rs`) looks like it might be generated; is it?

**Review by Jake-Shadle — APPROVED** [review]
Thanks!

**Comment by hoijui** [comment]
thank you! :-)
... lots to learn here.. will maybe use your lints too for my projects. :-)
It seems to me, that your `update` program works similarly like `build.rs`. You do it this way because it is more... flexible/powerful somehow?

**Comment by Jake-Shadle** [comment]
Build.rs would be run for all builds that depend on this project, which (in this case) is also doing network calls, which are something that should never be done during a build. The SPDX list is only updated a few times a year, so it's vastly easier to just update it manually.

**Pull request merged**
