### PR TITLE
FEATURE: Add Copyleft flag

### PR DESCRIPTION
**Pull request by kain88-de**
Adds a copyleft flag for all GPL based licenses.

I additionally moved the definition of the flags into the identifiers
file. This change lets me use bit operations to clearly mark the
licenses, without doing calculations in my head.

Fixes: #8

Question: Should the CC Share-Alike licenses be marked as well?

### CODE REVIEW

**Comment by Jake-Shadle** [comment]
Hey, thanks for the PR! I should have clarified in #8 that the flag should be added in the update binary in this repo so that the flag doesn't need to be reapplied on top of identifiers.rs

**Comment by kain88-de** [comment]
Well I could have also just read the header. I can add the flag to the
update binary tomorrow.

**Comment by Jake-Shadle** [comment]
Awesome thanks!

**Comment by kain88-de** [comment]
My question renains thought. Should Cc share alike licenses be equally
treated as copy left?

**Comment by Jake-Shadle** [comment]
Yes, I believe it should be. But looking at the lists here https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses, maybe eventually the flag could be made a bit more nuanced with regards to distribution vs modification etc.

**Comment by kain88-de** [comment]
The only noticeable exceptions in that list is in the linking column.
Otherwise modification and distribution are always marked as copy left
together. The agpl v1 looks like an exception but the gnu agpl is always
copyleft, as stated later in the table.

Linking is a complicated topic, as far as I’m aware it is not legally clear
what linking means. You can even find arguments about what a link is for
interpreted languages like ruby and python online.  In this case I would
simply be on the cautious side and do not distinguish linking from other
use cases. A simple flag is better here.

**Comment by Jake-Shadle** [comment]
Yup, that sounds reasonable.

**Comment by kain88-de** [comment]
I updated the PR. The copyleft status is now set in the update binary based on the license name. For easier comparison of my changes, I also updated how the flags are set. Now the identifiers file lists the flags by name, this gives a much easier human-readable format IMHO.

**Pull request merged**
